import type { Metadata } from "next";
import { Inter, Grand_Hotel } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const grandHotel = Grand_Hotel({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Super site wow!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <h1 className={grandHotel.className}>Super titre</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
